# Generated by Django 5.2.8 on 2025-11-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Клиент')),
                ('deadline', models.DateField(verbose_name='Срок сдачи')),
                ('status', models.CharField(choices=[('not-ready', 'Не готов'), ('in-progress', 'В процессе'), ('ready', 'Готово')], default='not-ready', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('not-ready', 'Не готов'), ('in-progress', 'В процессе'), ('ready', 'Готово')], default='not-ready', max_length=20, verbose_name='Статус товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
            ],
        ),
    ]
