# Generated by Django 5.2.8 on 2025-11-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day_before_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления за день до срока'),
        ),
        migrations.AddField(
            model_name='profile',
            name='popup_notifications',
            field=models.BooleanField(default=True, verbose_name='Всплывающие уведомления'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sound_notifications',
            field=models.BooleanField(default=True, verbose_name='Звуковые уведомления'),
        ),
    ]
