# Generated by Django 5.2.8 on 2025-11-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_profile_day_before_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Логотип компании (для счетов)')),
            ],
            options={
                'verbose_name': 'Настройки компании',
                'verbose_name_plural': 'Настройки компании',
            },
        ),
    ]
