# Generated by Django 5.2.8 on 2025-11-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255, verbose_name='Token Telegram-бота')),
                ('chat_id', models.CharField(blank=True, max_length=255, verbose_name='Chat ID (куда отправлять уведомления)')),
            ],
            options={
                'verbose_name': 'Настройки Telegram',
                'verbose_name_plural': 'Настройки Telegram',
            },
        ),
    ]
