# Generated by Django 5.2.8 on 2025-11-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_telegramsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('category', models.CharField(choices=[('polygraphy', 'Полиграфия'), ('packaging', 'Упаковка'), ('souvenirs', 'Сувениры'), ('large-format', 'Широкоформатная печать')], max_length=50, verbose_name='Категория')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name="Класс иконки (напр. 'fas fa-print')")),
            ],
            options={
                'verbose_name': 'Товар (ассортимент)',
                'verbose_name_plural': 'Товары (ассортимент)',
                'ordering': ['category', 'name'],
            },
        ),
    ]
