# Generated by Django 5.2.8 on 2025-11-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_responsible_user_item_responsible_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к товару'),
        ),
    ]
