# Generated by Django 5.2.8 on 2025-11-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_item_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='item',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности'),
        ),
    ]
