# Generated by Django 4.2.26 on 2025-11-18 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_item_is_archived_item_ready_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар заказа', 'verbose_name_plural': 'Товары заказа'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Товар (шаблон)', 'verbose_name_plural': 'Товары (шаблоны)'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('not-ready', 'Не готов'), ('in-progress', 'В процессе'), ('ready', 'Готово')], default='not-ready', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day_before_notifications',
            field=models.BooleanField(default=True, verbose_name='Напоминание за день'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='popup_notifications',
            field=models.BooleanField(default=True, verbose_name='Всплывающие окна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sound_notifications',
            field=models.BooleanField(default=True, verbose_name='Звук'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chat ID'),
        ),
    ]
